export const AUTH = {
  SET_USER_DATA: "SET_USER_DATA",
  SHOW_LOGIN_MODAL: "SHOW_LOGIN_MODAL",
  SHOW_REGISTER_MODAL: "SHOW_REGISTER_MODAL",
  CLOSE_LOGIN_REGISTER: "CLOSE_LOGIN_REGISTER",
  LOGIN_GUEST: "LOGIN_GUEST",
  LOG_OUT: "LOG_OUT",
};

export const QUIZ = {
  SET_QUIZ_LIST: "SET_QUIZ_LIST",
  SET_SCORE_HISTORY: "SET_SCORE_HISTORY",
  ADD_SCORE_CARD: "ADD_SCORE_CARD",
};
